spring:
  application:
    name: ApiGateway

  config:
    import: optional:configserver:http://3.111.171.10:8888

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://main.d1gezrhyyl9lz2.amplifyapp.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true